package com.speeduino.manager.desktop.feature.maps

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.FilledTonalButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.speeduino.manager.desktop.DesktopSpeeduinoController
import com.speeduino.manager.desktop.LocalStrings
import com.speeduino.manager.desktop.ui.DropdownField
import com.speeduino.manager.desktop.ui.NumberField
import com.speeduino.manager.model.basemap.BaseMapAdjustments
import com.speeduino.manager.model.basemap.BaseMapGenerator
import com.speeduino.manager.model.basemap.EngineProfile
import com.speeduino.manager.model.basemap.FuelType
import com.speeduino.manager.model.basemap.GeneratedBaseMap

@Composable
internal fun BaseMapWizardScreenDesktop(controller: DesktopSpeeduinoController) {
    val engineConstants by controller.engineConstants.collectAsState()
    val strings = LocalStrings.current
    var cylinders by remember { mutableStateOf("4") }
    var displacement by remember { mutableStateOf("2000") }
    var maxRpm by remember { mutableStateOf("6500") }
    var compression by remember { mutableStateOf("10.5") }
    var injectorFlow by remember { mutableStateOf("28") }
    var mapMax by remember { mutableStateOf("110") }
    var fuelType by remember { mutableStateOf(FuelType.GASOLINE) }
    var richness by remember { mutableStateOf("0.0") }
    var advanceOffset by remember { mutableStateOf("0.0") }
    var aggressiveness by remember { mutableStateOf("0.0") }
    var generated by remember { mutableStateOf<GeneratedBaseMap?>(null) }

    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
        Surface(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(18.dp),
            color = MaterialTheme.colorScheme.surfaceVariant,
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.4f))
        ) {
            Column(
                modifier = Modifier.fillMaxWidth().padding(20.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text(
                    strings["label.baseMapTitle"],
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = androidx.compose.ui.text.font.FontWeight.Medium
                )
                Text(strings["label.baseMapSubtitle"], style = MaterialTheme.typography.bodyMedium)
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NumberField(strings["label.cylinders"], cylinders, { cylinders = it }, Modifier.width(140.dp))
                    NumberField(strings["label.displacementCc"], displacement, { displacement = it }, Modifier.width(160.dp))
                    NumberField(strings["label.rpmMax"], maxRpm, { maxRpm = it }, Modifier.width(140.dp))
                }
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NumberField(strings["label.compression"], compression, { compression = it }, Modifier.width(140.dp))
                    NumberField(strings["label.injectorFlow"], injectorFlow, { injectorFlow = it }, Modifier.width(160.dp))
                    NumberField(strings["label.mapMaxKpa"], mapMax, { mapMax = it }, Modifier.width(140.dp))
                }
                DropdownField(
                    strings["label.fuel"],
                    fuelType.name,
                    FuelType.values().map { it.name }
                ) { label ->
                    fuelType = FuelType.valueOf(label)
                }
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NumberField(strings["label.richness"], richness, { richness = it }, Modifier.width(140.dp))
                    NumberField(strings["label.advanceOffset"], advanceOffset, { advanceOffset = it }, Modifier.width(160.dp))
                    NumberField(strings["label.highLoadAgg"], aggressiveness, { aggressiveness = it }, Modifier.width(160.dp))
                }
                FilledTonalButton(
                    onClick = {
                        val profile = EngineProfile(
                            cylinders = cylinders.toIntOrNull() ?: 4,
                            displacementCc = displacement.toDoubleOrNull() ?: 2000.0,
                            maxRpm = maxRpm.toIntOrNull() ?: 6500,
                            compressionRatio = compression.toDoubleOrNull() ?: 10.5,
                            fuelType = fuelType,
                            injectorFlowLbsPerHour = injectorFlow.toDoubleOrNull() ?: 28.0,
                            mapMaxKpa = mapMax.toIntOrNull() ?: 110
                        )
                        val adjustments = BaseMapAdjustments(
                            richness = richness.toDoubleOrNull() ?: 0.0,
                            advanceOffset = advanceOffset.toDoubleOrNull() ?: 0.0,
                            highLoadAggressiveness = aggressiveness.toDoubleOrNull() ?: 0.0
                        )
                        generated = BaseMapGenerator().generate(profile, engineConstants, adjustments)
                    }
                ) { Text(strings["action.generateMaps"]) }
            }
        }

        generated?.let { map ->
            Surface(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(18.dp),
                color = MaterialTheme.colorScheme.surface,
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.35f))
            ) {
                Column(
                    modifier = Modifier.fillMaxWidth().padding(20.dp),
                    verticalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Text(strings["label.baseMapResult"], style = MaterialTheme.typography.titleMedium)
                    Text(strings.format("label.reqFuel", map.engineConstants.reqFuel))
                    Text(strings.format("label.stoich", map.engineConstants.stoichiometricRatio))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        FilledTonalButton(onClick = { controller.applyGeneratedBaseMap(map) }) { Text(strings["action.applyAll"]) }
                        FilledTonalButton(onClick = { controller.applyGeneratedBaseMap(map, writeConstants = false) }) { Text(strings["action.applyMaps"]) }
                        FilledTonalButton(onClick = { controller.applyGeneratedBaseMap(map, writeTables = false) }) { Text(strings["action.applyConstants"]) }
                    }
                }
            }
        }
    }
}
