package com.speeduino.manager.desktop

import androidx.compose.runtime.staticCompositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.util.Locale
import java.util.Properties

enum class AppLanguage(val code: String) {
    EN("en"),
    PT("pt"),
    ES("es"),
    FR("fr"),
    ID("id"),
    ZH("zh");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return when (code?.lowercase(Locale.US)) {
                "pt" -> PT
                "es" -> ES
                "fr" -> FR
                "id" -> ID
                "in" -> ID
                "zh" -> ZH
                else -> EN
            }
        }
    }
}

class Strings(private val entries: Map<String, String>) {
    operator fun get(key: String): String = entries[key] ?: key

    fun format(key: String, vararg args: Any): String {
        return String.format(Locale.US, get(key), *args)
    }
}

val LocalStrings = staticCompositionLocalOf {
    Strings(Translations.EN)
}

object Translations {
    val EN = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Settings",
        "app.settingsTitle" to "App Settings",
        "app.languageLabel" to "Idioma",
        "app.languageEnglish" to "Inglés",
        "app.languagePortuguese" to "Portugués",
        "app.languageSpanish" to "Español",
        "app.languageFrench" to "Francés",
        "app.languageIndonesian" to "Indonesio",
        "app.languageChinese" to "Chino",
        "app.languageSpanish" to "Spanish",
        "app.languageFrench" to "French",
        "app.languageIndonesian" to "Indonesian",
        "app.languageChinese" to "Chinese",
        "app.openDropdown" to "Open",
        "app.noOptions" to "No options",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "Dashboard",
        "nav.sectionMaps" to "Maps & Tables",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "Dashboard",
        "route.connection" to "Connection",
        "route.veTable" to "VE Table",
        "route.ignitionTable" to "Ignition Table",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "Engine Constants",
        "route.triggerSettings" to "Trigger",
        "route.sensorsConfig" to "Calibration",
        "route.engineProtection" to "Protection",
        "route.realTimeMonitor" to "Real Time Monitor",
        "route.logViewer" to "Log Viewer",
        "route.logAnalyzer" to "Log Analyzer",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "Connected",
        "status.disconnected" to "Disconnected",
        "status.connecting" to "Connecting...",
        "status.failed" to "Failed to connect: %s",
        "status.label" to "Status",
        "action.connect" to "Connect",
        "action.disconnect" to "Disconnect",
        "action.loadEcu" to "Load ECU",
        "action.saveEcu" to "Save ECU",
        "action.apply" to "Apply",
        "action.cancel" to "Cancel",
        "action.save" to "Save",
        "action.open" to "Open",
        "action.startCapture" to "Start capture",
        "action.stopCapture" to "Stop capture",
        "action.exportLog" to "Export log",
        "action.saveCsv" to "Save CSV",
        "action.refreshSnapshot" to "Refresh snapshot",
        "action.generateMaps" to "Generate maps",
        "action.applyAll" to "Apply all",
        "action.applyMaps" to "Apply maps",
        "action.applyConstants" to "Apply constants",
        "action.downloadConfig" to "Download session",
        "action.exportConfig" to "Export backup",
        "action.importConfig" to "Import session",
        "action.useLocal" to "Use local",
        "action.useEcu" to "Use ECU",
        "action.load" to "Load",
        "action.editValue" to "Edit value",
        "action.analyze" to "Analyze",
        "action.compare" to "Compare",
        "action.applyToVe" to "Apply to VE",
        "label.diagnostics" to "Diagnostics",
        "label.firmware" to "Firmware",
        "label.product" to "Product",
        "label.connection" to "Connection",
        "label.appVersion" to "App version",
        "label.errorWithValue" to "Error: %s",
        "label.host" to "Host",
        "label.port" to "Port",
        "label.portInvalid" to "Invalid port",
        "label.serialPort" to "Serial port",
        "label.connectionType" to "Connection type",
        "label.baud" to "Baud",
        "label.intervalMs" to "Interval (ms)",
        "label.fileName" to "File name",
        "label.captureCount" to "Captures: %d",
        "label.samples" to "Samples: %d",
        "label.duration" to "Duration: %ds",
        "label.start" to "Start: %s",
        "label.end" to "End: %s",
        "label.currentStatus" to "Current status",
        "label.backupTitle" to "Backup & Restore",
        "label.backupSubtitle" to "Save and restore ECU sessions (.zip with .bin pages).",
        "label.backupSaveTitle" to "Save backup",
        "label.backupOpenTitle" to "Open backup",
        "label.configProgress" to "Progress: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Session Conflict",
        "label.syncDialogMessage" to "Local session differs from ECU. Which one should be used?",
        "label.noDataLoaded" to "No data loaded.",
        "label.noLogCaptured" to "No log captured.",
        "label.selectSignals" to "Select signals to plot.",
        "label.noData" to "--",
        "label.snapshotTitle" to "Log Viewer",
        "label.snapshotSubtitle" to "Current capture snapshot in memory.",
        "label.logAnalyzerTitle" to "Log Analyzer",
        "label.logAnalyzerSubtitle" to "Analyze a CSV log and suggest VE updates using the shared analyzer.",
        "label.logAnalyzerNoFile" to "No log selected.",
        "label.logSignalsSelect" to "Signals to include in CSV",
        "label.analyzerLoading" to "Processing CSV. Large logs can take a while...",
        "label.logAnalyzerOpenTitle" to "Open log CSV",
        "label.logAnalyzerSummary" to "Analysis summary",
        "label.beforeAfterTitle" to "Before-After Compare",
        "label.beforeAfterSubtitle" to "Compare two logs and visualize AFR error improvement by cell.",
        "label.beforeAfterPickBefore" to "Select BEFORE log CSV",
        "label.beforeAfterPickAfter" to "Select AFTER log CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Comparison summary",
        "label.beforeAfterHeatmap" to "Comparison heatmap",
        "label.beforeAfterCell" to "Cell row %d col %d",
        "label.beforeAfterCellBefore" to "Before abs error: %.3f (%d samples)",
        "label.beforeAfterCellAfter" to "After abs error: %.3f (%d samples)",
        "label.beforeAfterMetricAfrError" to "Avg abs AFR error | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Lean time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Rich time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Coverage | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Strategy",
        "label.analyzerSignals" to "Signal readiness",
        "label.heatmapTitle" to "Heatmap (VE delta)",
        "label.heatmapCellInfo" to "RPM %d | Load %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Cluster suggestions",
        "label.noSuggestions" to "No cluster suggestions for this log.",
        "label.clusterDelta" to "Delta: %d%% | Avg hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Samples used: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duration: %.1fs",
        "label.rpmRange" to "RPM range: %d - %d",
        "label.loadRange" to "Load range: %d - %d %s",
        "label.monitorTitle" to "Real Time Monitor",
        "label.monitorSubtitle" to "Live data capture and monitoring.",
        "label.engineProtectionTitle" to "Engine Protection & Limiters",
        "label.engineProtectionSubtitle" to "Safety protections and engine limiters.",
        "label.connectionScreenTitle" to "Connection",
        "label.engineConstantsTitle" to "Engine Constants",
        "label.engineConstantsSubtitle" to "Global engine and fuel parameters.",
        "label.triggerTitle" to "Trigger",
        "label.triggerSubtitle" to "RPM sensor configuration.",
        "label.triggerVisualPreview" to "Trigger visual preview",
        "label.triggerVisualApproximation" to "Preview approximation for this trigger pattern.",
        "label.triggerVisualInvalidInput" to "Invalid trigger input (check teeth values).",
        "label.triggerWheelPreview" to "Wheel preview",
        "label.triggerSignalPreview" to "Signal preview",
        "label.syncMarker" to "Sync marker",
        "label.tdcMarker" to "TDC marker",
        "label.missingWindow" to "Missing gap",
        "label.syncToothFormat" to "Sync tooth: %d",
        "label.effectiveTriggerAngleFormat" to "Effective trigger angle: %d deg (angle x multiplier)",
        "label.cycleScopeFormat" to "Displayed scope: %.0f deg crank per wheel revolution",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Generate base maps from the engine profile.",
        "label.baseMapResult" to "Result",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "Req Fuel (ms)",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Recommended range: %s..%s",
        "label.mapVe" to "Fuel map (VE).",
        "label.mapIgnition" to "Ignition map (degrees BTDC).",
        "label.mapAfr" to "AFR target map (lambda).",
        "label.mapAndStoich" to "MAP and stoichiometry",
        "label.fuelAndReference" to "Fuel and reference",
        "label.algorithmAndInjection" to "Algorithm and injection",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "Trigger Edge",
        "label.triggerFilter" to "Trigger Filter",
        "label.triggerPattern" to "Trigger Pattern",
        "label.skipRevolutions" to "Skip Revolutions",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "Missing Teeth",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Type %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Select",
        "label.tps" to "TPS",
        "label.map" to "MAP",
        "label.afrTarget" to "AFR Target",
        "label.rpm" to "RPM",
        "label.tableInvert" to "Invert table order",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.tableInvert" to "Inverter ordem da tabela",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "Fuel",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "Injectors",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algorithm",
        "label.fuel" to "Fuel",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAP",
        "label.voltage" to "Voltage",
        "label.battery" to "Battery",
        "label.cylinders" to "Cylinders",
        "label.displacementCc" to "Displacement cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compression",
        "label.engineType" to "Engine type",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primary phase high",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Polling",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "No captured samples yet. Start capture and wait a few seconds.",
        "label.logSaveSuccess" to "CSV saved: %s",
        "label.logSaveError" to "Error saving CSV: %s",
        "label.lastSavedLogPath" to "Last saved CSV: %s",
        "label.sensorsNotSupported" to "Sensor calibration not supported on desktop yet.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "Port",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB Serial",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB Serial",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "Port",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "Maps & Tables",
        "label.dashboard" to "Dashboard",
        "label.app" to "App",
        "label.ignition" to "Ignition",
        "label.channel2" to "Channel 2",
        "label.channel3" to "Channel 3",
        "label.channel4" to "Channel 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth"
    )

    val PT = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Configuracoes",
        "app.settingsTitle" to "Configuracoes do App",
        "app.languageLabel" to "Idioma",
        "app.languageEnglish" to "Inglês",
        "app.languagePortuguese" to "Português",
        "app.languageSpanish" to "Espanhol",
        "app.languageFrench" to "Francês",
        "app.languageIndonesian" to "Indonésio",
        "app.languageChinese" to "Chinês",
        "app.openDropdown" to "Abrir",
        "app.noOptions" to "Nenhuma opcao",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "Dashboard",
        "nav.sectionMaps" to "Mapas & Tabelas",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "Dashboard",
        "route.connection" to "Conexao",
        "route.veTable" to "VE Table",
        "route.ignitionTable" to "Ignition Table",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "Constantes do Motor",
        "route.triggerSettings" to "Gatilho",
        "route.sensorsConfig" to "Calibracao",
        "route.engineProtection" to "Protecao",
        "route.realTimeMonitor" to "Monitor em Tempo Real",
        "route.logViewer" to "Visualizador de Logs",
        "route.logAnalyzer" to "Analisador de Logs",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "Conectado",
        "status.disconnected" to "Desconectado",
        "status.connecting" to "Conectando...",
        "status.failed" to "Falha ao conectar: %s",
        "status.label" to "Status",
        "action.connect" to "Conectar",
        "action.disconnect" to "Desconectar",
        "action.loadEcu" to "Carregar ECU",
        "action.saveEcu" to "Salvar ECU",
        "action.apply" to "Aplicar",
        "action.cancel" to "Cancelar",
        "action.save" to "Salvar",
        "action.open" to "Abrir",
        "action.startCapture" to "Iniciar captura",
        "action.stopCapture" to "Parar captura",
        "action.exportLog" to "Exportar log",
        "action.saveCsv" to "Salvar CSV",
        "action.refreshSnapshot" to "Atualizar snapshot",
        "action.generateMaps" to "Gerar mapas",
        "action.applyAll" to "Aplicar tudo",
        "action.applyMaps" to "Aplicar mapas",
        "action.applyConstants" to "Aplicar constantes",
        "action.downloadConfig" to "Baixar sessao",
        "action.exportConfig" to "Exportar backup",
        "action.importConfig" to "Importar sessao",
        "action.useLocal" to "Usar local",
        "action.useEcu" to "Usar ECU",
        "action.load" to "Carregar",
        "action.editValue" to "Editar valor",
        "action.analyze" to "Analisar",
        "action.compare" to "Comparar",
        "action.applyToVe" to "Aplicar na VE",
        "label.diagnostics" to "Diagnostico",
        "label.firmware" to "Firmware",
        "label.product" to "Produto",
        "label.connection" to "Conexao",
        "label.appVersion" to "Versao do app",
        "label.errorWithValue" to "Erro: %s",
        "label.host" to "Host",
        "label.port" to "Porta",
        "label.portInvalid" to "Porta invalida",
        "label.serialPort" to "Porta serial",
        "label.connectionType" to "Tipo de conexao",
        "label.baud" to "Baud",
        "label.intervalMs" to "Intervalo (ms)",
        "label.fileName" to "Nome do arquivo",
        "label.captureCount" to "Capturas: %d",
        "label.samples" to "Amostras: %d",
        "label.duration" to "Duracao: %ds",
        "label.start" to "Inicio: %s",
        "label.end" to "Fim: %s",
        "label.currentStatus" to "Status Atual",
        "label.backupTitle" to "Backup e Restauracao",
        "label.backupSubtitle" to "Salva e restaura sessoes da ECU (.zip com paginas .bin).",
        "label.backupSaveTitle" to "Salvar backup",
        "label.backupOpenTitle" to "Abrir backup",
        "label.configProgress" to "Progresso: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Conflito de Sessao",
        "label.syncDialogMessage" to "Sessao local difere da ECU. Qual deseja usar?",
        "label.noDataLoaded" to "Nenhum dado carregado.",
        "label.noLogCaptured" to "Nenhum log capturado.",
        "label.selectSignals" to "Selecione sinais para plotar.",
        "label.noData" to "--",
        "label.snapshotTitle" to "Visualizador de Logs",
        "label.snapshotSubtitle" to "Snapshot atual da captura em memoria.",
        "label.logAnalyzerTitle" to "Analisador de Logs",
        "label.logAnalyzerSubtitle" to "Analise um CSV e sugira ajustes na VE usando o analisador compartilhado.",
        "label.logAnalyzerNoFile" to "Nenhum log selecionado.",
        "label.logSignalsSelect" to "Sinais para incluir no CSV",
        "label.analyzerLoading" to "Processando CSV. Logs grandes podem demorar...",
        "label.logAnalyzerOpenTitle" to "Abrir log CSV",
        "label.logAnalyzerSummary" to "Resumo da analise",
        "label.beforeAfterTitle" to "Comparativo Before-After",
        "label.beforeAfterSubtitle" to "Compare dois logs e visualize melhora/piora do erro AFR por celula.",
        "label.beforeAfterPickBefore" to "Selecionar log BEFORE CSV",
        "label.beforeAfterPickAfter" to "Selecionar log AFTER CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Resumo da comparacao",
        "label.beforeAfterHeatmap" to "Heatmap da comparacao",
        "label.beforeAfterCell" to "Celula linha %d coluna %d",
        "label.beforeAfterCellBefore" to "Erro AFR abs Before: %.3f (%d amostras)",
        "label.beforeAfterCellAfter" to "Erro AFR abs After: %.3f (%d amostras)",
        "label.beforeAfterMetricAfrError" to "Erro AFR abs medio | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Tempo lean | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Tempo rich | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Cobertura | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Estrategia",
        "label.analyzerSignals" to "Estado dos sinais",
        "label.heatmapTitle" to "Heatmap (delta VE)",
        "label.heatmapCellInfo" to "RPM %d | Carga %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Sugestoes por cluster",
        "label.noSuggestions" to "Sem sugestoes de cluster para este log.",
        "label.clusterDelta" to "Delta: %d%% | Media de hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Amostras usadas: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duracao: %.1fs",
        "label.rpmRange" to "Faixa RPM: %d - %d",
        "label.loadRange" to "Faixa carga: %d - %d %s",
        "label.monitorTitle" to "Monitor em Tempo Real",
        "label.monitorSubtitle" to "Captura e monitoramento de live data.",
        "label.engineProtectionTitle" to "Engine Protection & Limiters",
        "label.engineProtectionSubtitle" to "Protecoes de seguranca e limitadores do motor.",
        "label.connectionScreenTitle" to "Conexao",
        "label.engineConstantsTitle" to "Constantes do Motor",
        "label.engineConstantsSubtitle" to "Parametros globais do motor e injecao.",
        "label.triggerTitle" to "Gatilho",
        "label.triggerSubtitle" to "Configuracao de sensor de rotacao.",
        "label.triggerVisualPreview" to "Preview visual do trigger",
        "label.triggerVisualApproximation" to "Preview aproximado para este padrao de trigger.",
        "label.triggerVisualInvalidInput" to "Entrada invalida do trigger (verifique dentes).",
        "label.triggerWheelPreview" to "Preview da roda",
        "label.triggerSignalPreview" to "Preview do sinal",
        "label.syncMarker" to "Marcador sync",
        "label.tdcMarker" to "Marcador PMS",
        "label.missingWindow" to "Janela faltante",
        "label.syncToothFormat" to "Dente de sync: %d",
        "label.effectiveTriggerAngleFormat" to "Angulo efetivo do trigger: %d graus (angulo x multiplicador)",
        "label.cycleScopeFormat" to "Escopo exibido: %.0f graus por volta da roda",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Gera mapas base a partir do perfil do motor.",
        "label.baseMapResult" to "Resultado",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "Req Fuel (ms)",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Faixa recomendada: %s..%s",
        "label.mapVe" to "Mapa de combustivel (VE).",
        "label.mapIgnition" to "Mapa de ignicao (graus BTDC).",
        "label.mapAfr" to "Mapa de metas AFR (lambda).",
        "label.mapAndStoich" to "MAP e estequiometria",
        "label.fuelAndReference" to "Combustivel e referencia",
        "label.algorithmAndInjection" to "Algoritmo e injecao",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "Trigger Edge",
        "label.triggerFilter" to "Trigger Filter",
        "label.triggerPattern" to "Trigger Pattern",
        "label.skipRevolutions" to "Skip Revolutions",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "Missing Teeth",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Tipo %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Selecione",
        "label.tps" to "TPS",
        "label.map" to "MAP",
        "label.afrTarget" to "AFR Alvo",
        "label.rpm" to "RPM",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "Fuel",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "Injetores",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algoritmo",
        "label.fuel" to "Combustivel",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAP",
        "label.voltage" to "Voltagem",
        "label.battery" to "Bateria",
        "label.cylinders" to "Cilindros",
        "label.displacementCc" to "Cilindrada cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compressao",
        "label.engineType" to "Tipo Motor",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primeira fase alta",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Poll level",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "Sem amostras capturadas ainda. Inicie a captura e aguarde alguns segundos.",
        "label.logSaveSuccess" to "CSV salvo: %s",
        "label.logSaveError" to "Erro ao salvar CSV: %s",
        "label.lastSavedLogPath" to "Ultimo CSV salvo: %s",
        "label.sensorsNotSupported" to "Calibracao de sensores ainda nao suportada no desktop.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "Porta",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB Serial",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB Serial",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "Porta",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "Mapas & Tabelas",
        "label.dashboard" to "Dashboard",
        "label.app" to "App",
        "label.ignition" to "Ignicao",
        "label.channel2" to "Canal 2",
        "label.channel3" to "Canal 3",
        "label.channel4" to "Canal 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth"
    )

    val ES = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Settings",
        "app.settingsTitle" to "App Settings",
        "app.languageLabel" to "Langue",
        "app.languageEnglish" to "Anglais",
        "app.languagePortuguese" to "Portugais",
        "app.languageSpanish" to "Espagnol",
        "app.languageFrench" to "Français",
        "app.languageIndonesian" to "Indonésien",
        "app.languageChinese" to "Chinois",
        "app.openDropdown" to "Abrir",
        "app.noOptions" to "No options",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "Panel",
        "nav.sectionMaps" to "Mapas & Tablas",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "Panel",
        "route.connection" to "Connection",
        "route.veTable" to "Tabla VE",
        "route.ignitionTable" to "Mesa de ignición",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "Constantes del motor",
        "route.triggerSettings" to "Trigger",
        "route.sensorsConfig" to "Calibración",
        "route.engineProtection" to "Protection",
        "route.realTimeMonitor" to "Real Time Monitor",
        "route.logViewer" to "Visor de registro",
        "route.logAnalyzer" to "Log Analyzer",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "Conectado",
        "status.disconnected" to "Desconectado",
        "status.connecting" to "Connecting...",
        "status.failed" to "Failed to connect: %s",
        "status.label" to "Status",
        "action.connect" to "Conectar",
        "action.disconnect" to "Desconectar",
        "action.loadEcu" to "Load ECU",
        "action.saveEcu" to "Save ECU",
        "action.apply" to "Aplicar",
        "action.cancel" to "Cancelar",
        "action.save" to "Guardar",
        "action.open" to "Abrir",
        "action.startCapture" to "Iniciar captura",
        "action.stopCapture" to "Detener captura",
        "action.exportLog" to "Export log",
        "action.saveCsv" to "Save CSV",
        "action.refreshSnapshot" to "Refresh snapshot",
        "action.generateMaps" to "Generate maps",
        "action.applyAll" to "Apply all",
        "action.applyMaps" to "Apply maps",
        "action.applyConstants" to "Apply constants",
        "action.downloadConfig" to "Download session",
        "action.exportConfig" to "Export backup",
        "action.importConfig" to "Import session",
        "action.useLocal" to "Use local",
        "action.useEcu" to "Use ECU",
        "action.load" to "Cargar",
        "action.editValue" to "Edit value",
        "action.analyze" to "Analyze",
        "action.compare" to "Compare",
        "action.applyToVe" to "Apply to VE",
        "label.diagnostics" to "Diagnóstico",
        "label.firmware" to "Firmware",
        "label.product" to "Product",
        "label.connection" to "Connection",
        "label.appVersion" to "App version",
        "label.errorWithValue" to "Error: %s",
        "label.host" to "Host",
        "label.port" to "Puerto",
        "label.portInvalid" to "Invalid port",
        "label.serialPort" to "Serial port",
        "label.connectionType" to "Connection type",
        "label.baud" to "Baud",
        "label.intervalMs" to "Interval (ms)",
        "label.fileName" to "File name",
        "label.captureCount" to "Captures: %d",
        "label.samples" to "Samples: %d",
        "label.duration" to "Duration: %ds",
        "label.start" to "Start: %s",
        "label.end" to "End: %s",
        "label.currentStatus" to "Current status",
        "label.backupTitle" to "Backup & Restore",
        "label.backupSubtitle" to "Save and restore ECU sessions (.zip with .bin pages).",
        "label.backupSaveTitle" to "Save backup",
        "label.backupOpenTitle" to "Open backup",
        "label.configProgress" to "Progress: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Session Conflict",
        "label.syncDialogMessage" to "Local session differs from ECU. Which one should be used?",
        "label.noDataLoaded" to "No data loaded.",
        "label.noLogCaptured" to "No log captured.",
        "label.selectSignals" to "Select signals to plot.",
        "label.noData" to "--",
        "label.snapshotTitle" to "Visor de registro",
        "label.snapshotSubtitle" to "Current capture snapshot in memory.",
        "label.logAnalyzerTitle" to "Log Analyzer",
        "label.logAnalyzerSubtitle" to "Analyze a CSV log and suggest VE updates using the shared analyzer.",
        "label.logAnalyzerNoFile" to "No log selected.",
        "label.logSignalsSelect" to "Signals to include in CSV",
        "label.analyzerLoading" to "Processing CSV. Large logs can take a while...",
        "label.logAnalyzerOpenTitle" to "Open log CSV",
        "label.logAnalyzerSummary" to "Analysis summary",
        "label.beforeAfterTitle" to "Before-After Compare",
        "label.beforeAfterSubtitle" to "Compare two logs and visualize AFR error improvement by cell.",
        "label.beforeAfterPickBefore" to "Select BEFORE log CSV",
        "label.beforeAfterPickAfter" to "Select AFTER log CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Comparison summary",
        "label.beforeAfterHeatmap" to "Comparison heatmap",
        "label.beforeAfterCell" to "Cell row %d col %d",
        "label.beforeAfterCellBefore" to "Before abs error: %.3f (%d samples)",
        "label.beforeAfterCellAfter" to "After abs error: %.3f (%d samples)",
        "label.beforeAfterMetricAfrError" to "Avg abs AFR error | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Lean time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Rich time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Coverage | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Strategy",
        "label.analyzerSignals" to "Signal readiness",
        "label.heatmapTitle" to "Heatmap (VE delta)",
        "label.heatmapCellInfo" to "RPM %d | Load %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Cluster suggestions",
        "label.noSuggestions" to "No cluster suggestions for this log.",
        "label.clusterDelta" to "Delta: %d%% | Avg hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Samples used: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duration: %.1fs",
        "label.rpmRange" to "RPM range: %d - %d",
        "label.loadRange" to "Load range: %d - %d %s",
        "label.monitorTitle" to "Real Time Monitor",
        "label.monitorSubtitle" to "Live data capture and monitoring.",
        "label.engineProtectionTitle" to "Protección y limitadores del motor",
        "label.engineProtectionSubtitle" to "Safety protections and engine limiters.",
        "label.connectionScreenTitle" to "Connection",
        "label.engineConstantsTitle" to "Constantes del motor",
        "label.engineConstantsSubtitle" to "Global engine and fuel parameters.",
        "label.triggerTitle" to "Trigger",
        "label.triggerSubtitle" to "RPM sensor configuration.",
        "label.triggerVisualPreview" to "Trigger visual preview",
        "label.triggerVisualApproximation" to "Preview approximation for this trigger pattern.",
        "label.triggerVisualInvalidInput" to "Invalid trigger input (check teeth values).",
        "label.triggerWheelPreview" to "Wheel preview",
        "label.triggerSignalPreview" to "Signal preview",
        "label.syncMarker" to "Sync marker",
        "label.tdcMarker" to "TDC marker",
        "label.missingWindow" to "Missing gap",
        "label.syncToothFormat" to "Sync tooth: %d",
        "label.effectiveTriggerAngleFormat" to "Effective trigger angle: %d deg (angle x multiplier)",
        "label.cycleScopeFormat" to "Displayed scope: %.0f deg crank per wheel revolution",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Generate base maps from the engine profile.",
        "label.baseMapResult" to "Result",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "Combustible requerido (ms)",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Recommended range: %s..%s",
        "label.mapVe" to "Fuel map (VE).",
        "label.mapIgnition" to "Ignition map (degrees BTDC).",
        "label.mapAfr" to "AFR target map (lambda).",
        "label.mapAndStoich" to "MAP and stoichiometry",
        "label.fuelAndReference" to "Fuel and reference",
        "label.algorithmAndInjection" to "Algorithm and injection",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "Borde del disparador",
        "label.triggerFilter" to "Filtro de disparo",
        "label.triggerPattern" to "Patrón de activación",
        "label.skipRevolutions" to "Saltar revoluciones",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "Dientes Perdidos",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Type %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Select",
        "label.tps" to "TPS",
        "label.map" to "MAPA",
        "label.afrTarget" to "Objetivo de AFR",
        "label.rpm" to "RPM",
        "label.tableInvert" to "Invert table order",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.tableInvert" to "Inverter ordem da tabela",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "Carburante",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "Inyectores",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algorithm",
        "label.fuel" to "Carburante",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAPA",
        "label.voltage" to "Voltage",
        "label.battery" to "Battery",
        "label.cylinders" to "Cilindros",
        "label.displacementCc" to "Displacement cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compression",
        "label.engineType" to "Engine type",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primary phase high",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Polling",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "No captured samples yet. Start capture and wait a few seconds.",
        "label.logSaveSuccess" to "CSV saved: %s",
        "label.logSaveError" to "Error saving CSV: %s",
        "label.lastSavedLogPath" to "Last saved CSV: %s",
        "label.sensorsNotSupported" to "Sensor calibration not supported on desktop yet.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "Puerto",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB/Serie",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB/Serie",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "Puerto",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "Mapas & Tablas",
        "label.dashboard" to "Panel",
        "label.app" to "App",
        "label.ignition" to "Ignition",
        "label.channel2" to "Channel 2",
        "label.channel3" to "Channel 3",
        "label.channel4" to "Channel 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth",
    )

    val FR = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Settings",
        "app.settingsTitle" to "App Settings",
        "app.languageLabel" to "Bahasa",
        "app.languageEnglish" to "Inggris",
        "app.languagePortuguese" to "Portugis",
        "app.languageSpanish" to "Spanyol",
        "app.languageFrench" to "Prancis",
        "app.languageIndonesian" to "Indonesia",
        "app.languageChinese" to "Cina",
        "app.openDropdown" to "Open",
        "app.noOptions" to "No options",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "Dashboard",
        "nav.sectionMaps" to "Maps & Tables",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "Dashboard",
        "route.connection" to "Connection",
        "route.veTable" to "VE Table",
        "route.ignitionTable" to "Ignition Table",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "Engine Constants",
        "route.triggerSettings" to "Trigger",
        "route.sensorsConfig" to "Calibration",
        "route.engineProtection" to "Protection",
        "route.realTimeMonitor" to "Real Time Monitor",
        "route.logViewer" to "Log Viewer",
        "route.logAnalyzer" to "Log Analyzer",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "Connected",
        "status.disconnected" to "Disconnected",
        "status.connecting" to "Connecting...",
        "status.failed" to "Failed to connect: %s",
        "status.label" to "Status",
        "action.connect" to "Connect",
        "action.disconnect" to "Disconnect",
        "action.loadEcu" to "Load ECU",
        "action.saveEcu" to "Save ECU",
        "action.apply" to "Apply",
        "action.cancel" to "Cancel",
        "action.save" to "Save",
        "action.open" to "Open",
        "action.startCapture" to "Iniciar captura",
        "action.stopCapture" to "Parar captura",
        "action.exportLog" to "Export log",
        "action.saveCsv" to "Save CSV",
        "action.refreshSnapshot" to "Refresh snapshot",
        "action.generateMaps" to "Generate maps",
        "action.applyAll" to "Apply all",
        "action.applyMaps" to "Apply maps",
        "action.applyConstants" to "Apply constants",
        "action.downloadConfig" to "Download session",
        "action.exportConfig" to "Export backup",
        "action.importConfig" to "Import session",
        "action.useLocal" to "Use local",
        "action.useEcu" to "Use ECU",
        "action.load" to "Load",
        "action.editValue" to "Edit value",
        "action.analyze" to "Analyze",
        "action.compare" to "Compare",
        "action.applyToVe" to "Apply to VE",
        "label.diagnostics" to "Diagnostics",
        "label.firmware" to "Firmware",
        "label.product" to "Product",
        "label.connection" to "Connection",
        "label.appVersion" to "App version",
        "label.errorWithValue" to "Error: %s",
        "label.host" to "Host",
        "label.port" to "Port",
        "label.portInvalid" to "Invalid port",
        "label.serialPort" to "Serial port",
        "label.connectionType" to "Connection type",
        "label.baud" to "Baud",
        "label.intervalMs" to "Interval (ms)",
        "label.fileName" to "File name",
        "label.captureCount" to "Captures: %d",
        "label.samples" to "Samples: %d",
        "label.duration" to "Duration: %ds",
        "label.start" to "Start: %s",
        "label.end" to "End: %s",
        "label.currentStatus" to "Current status",
        "label.backupTitle" to "Backup & Restore",
        "label.backupSubtitle" to "Save and restore ECU sessions (.zip with .bin pages).",
        "label.backupSaveTitle" to "Save backup",
        "label.backupOpenTitle" to "Open backup",
        "label.configProgress" to "Progress: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Session Conflict",
        "label.syncDialogMessage" to "Local session differs from ECU. Which one should be used?",
        "label.noDataLoaded" to "No data loaded.",
        "label.noLogCaptured" to "No log captured.",
        "label.selectSignals" to "Select signals to plot.",
        "label.noData" to "--",
        "label.snapshotTitle" to "Log Viewer",
        "label.snapshotSubtitle" to "Current capture snapshot in memory.",
        "label.logAnalyzerTitle" to "Log Analyzer",
        "label.logAnalyzerSubtitle" to "Analyze a CSV log and suggest VE updates using the shared analyzer.",
        "label.logAnalyzerNoFile" to "No log selected.",
        "label.logSignalsSelect" to "Signals to include in CSV",
        "label.analyzerLoading" to "Processing CSV. Large logs can take a while...",
        "label.logAnalyzerOpenTitle" to "Open log CSV",
        "label.logAnalyzerSummary" to "Analysis summary",
        "label.beforeAfterTitle" to "Before-After Compare",
        "label.beforeAfterSubtitle" to "Compare two logs and visualize AFR error improvement by cell.",
        "label.beforeAfterPickBefore" to "Select BEFORE log CSV",
        "label.beforeAfterPickAfter" to "Select AFTER log CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Comparison summary",
        "label.beforeAfterHeatmap" to "Comparison heatmap",
        "label.beforeAfterCell" to "Cell row %d col %d",
        "label.beforeAfterCellBefore" to "Before abs error: %.3f (%d samples)",
        "label.beforeAfterCellAfter" to "After abs error: %.3f (%d samples)",
        "label.beforeAfterMetricAfrError" to "Avg abs AFR error | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Lean time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Rich time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Coverage | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Strategy",
        "label.analyzerSignals" to "Signal readiness",
        "label.heatmapTitle" to "Heatmap (VE delta)",
        "label.heatmapCellInfo" to "RPM %d | Load %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Cluster suggestions",
        "label.noSuggestions" to "No cluster suggestions for this log.",
        "label.clusterDelta" to "Delta: %d%% | Avg hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Samples used: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duration: %.1fs",
        "label.rpmRange" to "RPM range: %d - %d",
        "label.loadRange" to "Load range: %d - %d %s",
        "label.monitorTitle" to "Real Time Monitor",
        "label.monitorSubtitle" to "Live data capture and monitoring.",
        "label.engineProtectionTitle" to "Engine Protection & Limiters",
        "label.engineProtectionSubtitle" to "Safety protections and engine limiters.",
        "label.connectionScreenTitle" to "Connection",
        "label.engineConstantsTitle" to "Engine Constants",
        "label.engineConstantsSubtitle" to "Global engine and fuel parameters.",
        "label.triggerTitle" to "Trigger",
        "label.triggerSubtitle" to "RPM sensor configuration.",
        "label.triggerVisualPreview" to "Trigger visual preview",
        "label.triggerVisualApproximation" to "Preview approximation for this trigger pattern.",
        "label.triggerVisualInvalidInput" to "Invalid trigger input (check teeth values).",
        "label.triggerWheelPreview" to "Wheel preview",
        "label.triggerSignalPreview" to "Signal preview",
        "label.syncMarker" to "Sync marker",
        "label.tdcMarker" to "TDC marker",
        "label.missingWindow" to "Missing gap",
        "label.syncToothFormat" to "Sync tooth: %d",
        "label.effectiveTriggerAngleFormat" to "Effective trigger angle: %d deg (angle x multiplier)",
        "label.cycleScopeFormat" to "Displayed scope: %.0f deg crank per wheel revolution",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Generate base maps from the engine profile.",
        "label.baseMapResult" to "Result",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "Req Fuel (ms)",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Recommended range: %s..%s",
        "label.mapVe" to "Fuel map (VE).",
        "label.mapIgnition" to "Ignition map (degrees BTDC).",
        "label.mapAfr" to "AFR target map (lambda).",
        "label.mapAndStoich" to "MAP and stoichiometry",
        "label.fuelAndReference" to "Fuel and reference",
        "label.algorithmAndInjection" to "Algorithm and injection",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "Trigger Edge",
        "label.triggerFilter" to "Trigger Filter",
        "label.triggerPattern" to "Trigger Pattern",
        "label.skipRevolutions" to "Skip Revolutions",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "Missing Teeth",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Type %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Select",
        "label.tps" to "TPS",
        "label.map" to "MAP",
        "label.afrTarget" to "AFR Target",
        "label.rpm" to "RPM",
        "label.tableInvert" to "Invert table order",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.tableInvert" to "Inverter ordem da tabela",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "Fuel",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "Injectors",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algorithm",
        "label.fuel" to "Fuel",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAP",
        "label.voltage" to "Voltage",
        "label.battery" to "Battery",
        "label.cylinders" to "Cylinders",
        "label.displacementCc" to "Displacement cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compression",
        "label.engineType" to "Engine type",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primary phase high",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Polling",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "No captured samples yet. Start capture and wait a few seconds.",
        "label.logSaveSuccess" to "CSV saved: %s",
        "label.logSaveError" to "Error saving CSV: %s",
        "label.lastSavedLogPath" to "Last saved CSV: %s",
        "label.sensorsNotSupported" to "Sensor calibration not supported on desktop yet.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "Port",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB Serial",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB Serial",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "Port",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "Maps & Tables",
        "label.dashboard" to "Dashboard",
        "label.app" to "App",
        "label.ignition" to "Ignition",
        "label.channel2" to "Channel 2",
        "label.channel3" to "Channel 3",
        "label.channel4" to "Channel 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth",
    )

    val ID = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Settings",
        "app.settingsTitle" to "App Settings",
        "app.languageLabel" to "语言",
        "app.languageEnglish" to "英语",
        "app.languagePortuguese" to "葡萄牙语",
        "app.languageSpanish" to "西班牙语",
        "app.languageFrench" to "法语",
        "app.languageIndonesian" to "印度尼西亚语",
        "app.languageChinese" to "中文",
        "app.openDropdown" to "Buka",
        "app.noOptions" to "No options",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "Dasbor",
        "nav.sectionMaps" to "Peta & Tabel",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "Dasbor",
        "route.connection" to "Connection",
        "route.veTable" to "Tabel VE",
        "route.ignitionTable" to "Tabel Pengapian",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "Konstanta Mesin",
        "route.triggerSettings" to "Trigger",
        "route.sensorsConfig" to "Kalibrasi",
        "route.engineProtection" to "Protection",
        "route.realTimeMonitor" to "Real Time Monitor",
        "route.logViewer" to "Penampil Log",
        "route.logAnalyzer" to "Log Analyzer",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "Terhubung",
        "status.disconnected" to "Terputus",
        "status.connecting" to "Connecting...",
        "status.failed" to "Failed to connect: %s",
        "status.label" to "Status",
        "action.connect" to "Hubungkan",
        "action.disconnect" to "Putuskan",
        "action.loadEcu" to "Load ECU",
        "action.saveEcu" to "Save ECU",
        "action.apply" to "Terapkan",
        "action.cancel" to "Batal",
        "action.save" to "Simpan",
        "action.open" to "Buka",
        "action.startCapture" to "Mulai perekaman",
        "action.stopCapture" to "Hentikan perekaman",
        "action.exportLog" to "Export log",
        "action.saveCsv" to "Save CSV",
        "action.refreshSnapshot" to "Refresh snapshot",
        "action.generateMaps" to "Generate maps",
        "action.applyAll" to "Apply all",
        "action.applyMaps" to "Apply maps",
        "action.applyConstants" to "Apply constants",
        "action.downloadConfig" to "Download session",
        "action.exportConfig" to "Export backup",
        "action.importConfig" to "Import session",
        "action.useLocal" to "Use local",
        "action.useEcu" to "Use ECU",
        "action.load" to "Muat",
        "action.editValue" to "Edit value",
        "action.analyze" to "Analyze",
        "action.compare" to "Compare",
        "action.applyToVe" to "Apply to VE",
        "label.diagnostics" to "Diagnostik",
        "label.firmware" to "Firmware",
        "label.product" to "Product",
        "label.connection" to "Connection",
        "label.appVersion" to "App version",
        "label.errorWithValue" to "Error: %s",
        "label.host" to "Host",
        "label.port" to "Port",
        "label.portInvalid" to "Invalid port",
        "label.serialPort" to "Serial port",
        "label.connectionType" to "Connection type",
        "label.baud" to "Baud",
        "label.intervalMs" to "Interval (ms)",
        "label.fileName" to "File name",
        "label.captureCount" to "Captures: %d",
        "label.samples" to "Samples: %d",
        "label.duration" to "Duration: %ds",
        "label.start" to "Start: %s",
        "label.end" to "End: %s",
        "label.currentStatus" to "Current status",
        "label.backupTitle" to "Backup & Restore",
        "label.backupSubtitle" to "Save and restore ECU sessions (.zip with .bin pages).",
        "label.backupSaveTitle" to "Save backup",
        "label.backupOpenTitle" to "Open backup",
        "label.configProgress" to "Progress: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Session Conflict",
        "label.syncDialogMessage" to "Local session differs from ECU. Which one should be used?",
        "label.noDataLoaded" to "No data loaded.",
        "label.noLogCaptured" to "No log captured.",
        "label.selectSignals" to "Select signals to plot.",
        "label.noData" to "--",
        "label.snapshotTitle" to "Penampil Log",
        "label.snapshotSubtitle" to "Current capture snapshot in memory.",
        "label.logAnalyzerTitle" to "Log Analyzer",
        "label.logAnalyzerSubtitle" to "Analyze a CSV log and suggest VE updates using the shared analyzer.",
        "label.logAnalyzerNoFile" to "No log selected.",
        "label.logSignalsSelect" to "Signals to include in CSV",
        "label.analyzerLoading" to "Processing CSV. Large logs can take a while...",
        "label.logAnalyzerOpenTitle" to "Open log CSV",
        "label.logAnalyzerSummary" to "Analysis summary",
        "label.beforeAfterTitle" to "Before-After Compare",
        "label.beforeAfterSubtitle" to "Compare two logs and visualize AFR error improvement by cell.",
        "label.beforeAfterPickBefore" to "Select BEFORE log CSV",
        "label.beforeAfterPickAfter" to "Select AFTER log CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Comparison summary",
        "label.beforeAfterHeatmap" to "Comparison heatmap",
        "label.beforeAfterCell" to "Cell row %d col %d",
        "label.beforeAfterCellBefore" to "Before abs error: %.3f (%d samples)",
        "label.beforeAfterCellAfter" to "After abs error: %.3f (%d samples)",
        "label.beforeAfterMetricAfrError" to "Avg abs AFR error | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Lean time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Rich time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Coverage | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Strategy",
        "label.analyzerSignals" to "Signal readiness",
        "label.heatmapTitle" to "Heatmap (VE delta)",
        "label.heatmapCellInfo" to "RPM %d | Load %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Cluster suggestions",
        "label.noSuggestions" to "No cluster suggestions for this log.",
        "label.clusterDelta" to "Delta: %d%% | Avg hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Samples used: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duration: %.1fs",
        "label.rpmRange" to "RPM range: %d - %d",
        "label.loadRange" to "Load range: %d - %d %s",
        "label.monitorTitle" to "Real Time Monitor",
        "label.monitorSubtitle" to "Live data capture and monitoring.",
        "label.engineProtectionTitle" to "Perlindungan Mesin & Pembatas",
        "label.engineProtectionSubtitle" to "Safety protections and engine limiters.",
        "label.connectionScreenTitle" to "Connection",
        "label.engineConstantsTitle" to "Konstanta Mesin",
        "label.engineConstantsSubtitle" to "Global engine and fuel parameters.",
        "label.triggerTitle" to "Trigger",
        "label.triggerSubtitle" to "RPM sensor configuration.",
        "label.triggerVisualPreview" to "Trigger visual preview",
        "label.triggerVisualApproximation" to "Preview approximation for this trigger pattern.",
        "label.triggerVisualInvalidInput" to "Invalid trigger input (check teeth values).",
        "label.triggerWheelPreview" to "Wheel preview",
        "label.triggerSignalPreview" to "Signal preview",
        "label.syncMarker" to "Sync marker",
        "label.tdcMarker" to "TDC marker",
        "label.missingWindow" to "Missing gap",
        "label.syncToothFormat" to "Sync tooth: %d",
        "label.effectiveTriggerAngleFormat" to "Effective trigger angle: %d deg (angle x multiplier)",
        "label.cycleScopeFormat" to "Displayed scope: %.0f deg crank per wheel revolution",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Generate base maps from the engine profile.",
        "label.baseMapResult" to "Result",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "Bahan bakar diperlukan (ms)",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Recommended range: %s..%s",
        "label.mapVe" to "Fuel map (VE).",
        "label.mapIgnition" to "Ignition map (degrees BTDC).",
        "label.mapAfr" to "AFR target map (lambda).",
        "label.mapAndStoich" to "MAP and stoichiometry",
        "label.fuelAndReference" to "Fuel and reference",
        "label.algorithmAndInjection" to "Algorithm and injection",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "Tepi Trigger",
        "label.triggerFilter" to "Filter Trigger",
        "label.triggerPattern" to "Pola Trigger",
        "label.skipRevolutions" to "Lewati Putaran",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "Gigi Hilang",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Type %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Select",
        "label.tps" to "TPS",
        "label.map" to "MAP",
        "label.afrTarget" to "Target AFR",
        "label.rpm" to "RPM",
        "label.tableInvert" to "Invert table order",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.tableInvert" to "Inverter ordem da tabela",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "Bahan bakar",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "Injektor",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algorithm",
        "label.fuel" to "Bahan bakar",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAP",
        "label.voltage" to "Voltage",
        "label.battery" to "Battery",
        "label.cylinders" to "Silinder",
        "label.displacementCc" to "Displacement cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compression",
        "label.engineType" to "Engine type",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primary phase high",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Polling",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "No captured samples yet. Start capture and wait a few seconds.",
        "label.logSaveSuccess" to "CSV saved: %s",
        "label.logSaveError" to "Error saving CSV: %s",
        "label.lastSavedLogPath" to "Last saved CSV: %s",
        "label.sensorsNotSupported" to "Sensor calibration not supported on desktop yet.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "Port",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB Serial",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB Serial",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "Port",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "Peta & Tabel",
        "label.dashboard" to "Dasbor",
        "label.app" to "App",
        "label.ignition" to "Ignition",
        "label.channel2" to "Channel 2",
        "label.channel3" to "Channel 3",
        "label.channel4" to "Channel 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth",
    )

    val ZH = mapOf(
        "app.windowTitle" to "SpeeduinoManager Desktop",
        "app.headerTitle" to "Speeduino Manager Desktop",
        "app.sidebarTitlePrimary" to "Speeduino",
        "app.sidebarTitleSecondary" to "Manager Desktop",
        "app.sectionTitle" to "SpeeduinoManager App",
        "app.settingsLabel" to "Settings",
        "app.settingsTitle" to "App Settings",
        "app.languageLabel" to "Language",
        "app.languageEnglish" to "English",
        "app.languagePortuguese" to "Portuguese",
        "app.openDropdown" to "打开",
        "app.noOptions" to "No options",
        "nav.sectionApp" to "App",
        "nav.sectionDashboard" to "仪表盘",
        "nav.sectionMaps" to "地图与表格",
        "nav.sectionConfigs" to "Configs",
        "nav.sectionLogs" to "Logs",
        "route.dashboard" to "仪表盘",
        "route.connection" to "Connection",
        "route.veTable" to "VE 表（容积效率）",
        "route.ignitionTable" to "点火表",
        "route.afrTable" to "AFR Table",
        "route.baseMapWizard" to "Base Map Wizard",
        "route.engineConstants" to "发动机常量",
        "route.triggerSettings" to "Trigger",
        "route.sensorsConfig" to "校准",
        "route.engineProtection" to "Protection",
        "route.realTimeMonitor" to "Real Time Monitor",
        "route.logViewer" to "日志查看器",
        "route.logAnalyzer" to "Log Analyzer",
        "route.beforeAfter" to "Before-After",
        "status.connected" to "已连接",
        "status.disconnected" to "未连接",
        "status.connecting" to "Connecting...",
        "status.failed" to "Failed to connect: %s",
        "status.label" to "状态",
        "action.connect" to "连接",
        "action.disconnect" to "断开连接",
        "action.loadEcu" to "Load ECU",
        "action.saveEcu" to "Save ECU",
        "action.apply" to "应用",
        "action.cancel" to "取消",
        "action.save" to "保存",
        "action.open" to "打开",
        "action.startCapture" to "开始采集",
        "action.stopCapture" to "停止采集",
        "action.exportLog" to "Export log",
        "action.saveCsv" to "Save CSV",
        "action.refreshSnapshot" to "Refresh snapshot",
        "action.generateMaps" to "Generate maps",
        "action.applyAll" to "Apply all",
        "action.applyMaps" to "Apply maps",
        "action.applyConstants" to "Apply constants",
        "action.downloadConfig" to "Download session",
        "action.exportConfig" to "Export backup",
        "action.importConfig" to "Import session",
        "action.useLocal" to "Use local",
        "action.useEcu" to "Use ECU",
        "action.load" to "加载",
        "action.editValue" to "Edit value",
        "action.analyze" to "Analyze",
        "action.compare" to "Compare",
        "action.applyToVe" to "Apply to VE",
        "label.diagnostics" to "诊断",
        "label.firmware" to "Firmware",
        "label.product" to "Product",
        "label.connection" to "Connection",
        "label.appVersion" to "App version",
        "label.errorWithValue" to "Error: %s",
        "label.host" to "主机",
        "label.port" to "端口",
        "label.portInvalid" to "Invalid port",
        "label.serialPort" to "Serial port",
        "label.connectionType" to "Connection type",
        "label.baud" to "Baud",
        "label.intervalMs" to "Interval (ms)",
        "label.fileName" to "File name",
        "label.captureCount" to "Captures: %d",
        "label.samples" to "Samples: %d",
        "label.duration" to "Duration: %ds",
        "label.start" to "Start: %s",
        "label.end" to "End: %s",
        "label.currentStatus" to "Current status",
        "label.backupTitle" to "Backup & Restore",
        "label.backupSubtitle" to "Save and restore ECU sessions (.zip with .bin pages).",
        "label.backupSaveTitle" to "Save backup",
        "label.backupOpenTitle" to "Open backup",
        "label.configProgress" to "Progress: %d%%",
        "label.configStatus" to "Status: %s",
        "label.syncDialogTitle" to "Session Conflict",
        "label.syncDialogMessage" to "Local session differs from ECU. Which one should be used?",
        "label.noDataLoaded" to "No data loaded.",
        "label.noLogCaptured" to "No log captured.",
        "label.selectSignals" to "Select signals to plot.",
        "label.noData" to "--",
        "label.snapshotTitle" to "日志查看器",
        "label.snapshotSubtitle" to "Current capture snapshot in memory.",
        "label.logAnalyzerTitle" to "Log Analyzer",
        "label.logAnalyzerSubtitle" to "Analyze a CSV log and suggest VE updates using the shared analyzer.",
        "label.logAnalyzerNoFile" to "No log selected.",
        "label.logSignalsSelect" to "Signals to include in CSV",
        "label.analyzerLoading" to "Processing CSV. Large logs can take a while...",
        "label.logAnalyzerOpenTitle" to "Open log CSV",
        "label.logAnalyzerSummary" to "Analysis summary",
        "label.beforeAfterTitle" to "Before-After Compare",
        "label.beforeAfterSubtitle" to "Compare two logs and visualize AFR error improvement by cell.",
        "label.beforeAfterPickBefore" to "Select BEFORE log CSV",
        "label.beforeAfterPickAfter" to "Select AFTER log CSV",
        "label.beforeAfterBefore" to "Before",
        "label.beforeAfterAfter" to "After",
        "label.beforeAfterSummary" to "Comparison summary",
        "label.beforeAfterHeatmap" to "Comparison heatmap",
        "label.beforeAfterCell" to "Cell row %d col %d",
        "label.beforeAfterCellBefore" to "Before abs error: %.3f (%d samples)",
        "label.beforeAfterCellAfter" to "After abs error: %.3f (%d samples)",
        "label.beforeAfterMetricAfrError" to "Avg abs AFR error | Before: %.3f  After: %.3f",
        "label.beforeAfterMetricLean" to "Lean time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricRich" to "Rich time ratio | Before: %.1f%%  After: %.1f%%",
        "label.beforeAfterMetricCoverage" to "Coverage | Before: %d/%d  After: %d/%d",
        "label.strategy" to "Strategy",
        "label.analyzerSignals" to "Signal readiness",
        "label.heatmapTitle" to "Heatmap (VE delta)",
        "label.heatmapCellInfo" to "RPM %d | Load %d | Delta %d%% | Hits %d",
        "label.clusterSuggestions" to "Cluster suggestions",
        "label.noSuggestions" to "No cluster suggestions for this log.",
        "label.clusterDelta" to "Delta: %d%% | Avg hits: %d",
        "label.preview" to "Preview",
        "label.samplesUsed" to "Samples used: %d / %d",
        "label.clustersCount" to "Clusters: %d",
        "label.durationSeconds" to "Duration: %.1fs",
        "label.rpmRange" to "RPM range: %d - %d",
        "label.loadRange" to "Load range: %d - %d %s",
        "label.monitorTitle" to "Real Time Monitor",
        "label.monitorSubtitle" to "Live data capture and monitoring.",
        "label.engineProtectionTitle" to "发动机保护与限值",
        "label.engineProtectionSubtitle" to "Safety protections and engine limiters.",
        "label.connectionScreenTitle" to "Connection",
        "label.engineConstantsTitle" to "发动机常量",
        "label.engineConstantsSubtitle" to "Global engine and fuel parameters.",
        "label.triggerTitle" to "Trigger",
        "label.triggerSubtitle" to "RPM sensor configuration.",
        "label.triggerVisualPreview" to "Trigger visual preview",
        "label.triggerVisualApproximation" to "Preview approximation for this trigger pattern.",
        "label.triggerVisualInvalidInput" to "Invalid trigger input (check teeth values).",
        "label.triggerWheelPreview" to "Wheel preview",
        "label.triggerSignalPreview" to "Signal preview",
        "label.syncMarker" to "Sync marker",
        "label.tdcMarker" to "TDC marker",
        "label.missingWindow" to "Missing gap",
        "label.syncToothFormat" to "Sync tooth: %d",
        "label.effectiveTriggerAngleFormat" to "Effective trigger angle: %d deg (angle x multiplier)",
        "label.cycleScopeFormat" to "Displayed scope: %.0f deg crank per wheel revolution",
        "label.baseMapTitle" to "Base Map Wizard",
        "label.baseMapSubtitle" to "Generate base maps from the engine profile.",
        "label.baseMapResult" to "Result",
        "label.reqFuel" to "ReqFuel: %.2f ms",
        "label.reqFuelMs" to "所需燃油（ms）",
        "label.stoich" to "Stoich: %.1f",
        "label.recommendedRange" to "Recommended range: %s..%s",
        "label.mapVe" to "Fuel map (VE).",
        "label.mapIgnition" to "Ignition map (degrees BTDC).",
        "label.mapAfr" to "AFR target map (lambda).",
        "label.mapAndStoich" to "MAP and stoichiometry",
        "label.fuelAndReference" to "Fuel and reference",
        "label.algorithmAndInjection" to "Algorithm and injection",
        "label.oddfireAngles" to "Oddfire Angles",
        "label.mapMaxKpa" to "MAP Max kPa",
        "label.mapSample" to "MAP Sample",
        "label.mapSwitch" to "MAP Switch",
        "label.rpmMax" to "RPM Max",
        "label.richness" to "Richness",
        "label.advanceOffset" to "Advance Offset",
        "label.highLoadAgg" to "High Load Agg.",
        "label.primarySpeed" to "Primary Speed",
        "label.secondaryEdge" to "Secondary Edge",
        "label.secondaryPattern" to "Secondary Pattern",
        "label.triggerAngle" to "Trigger Angle",
        "label.triggerEdge" to "触发沿",
        "label.triggerFilter" to "触发滤波",
        "label.triggerPattern" to "触发模式",
        "label.skipRevolutions" to "跳过转数",
        "label.pollLevel" to "Poll level",
        "label.baseTeeth" to "Base Teeth",
        "label.missingTeeth" to "缺齿",
        "label.missingTooth" to "Missing Tooth",
        "label.angleMultiplier" to "Angle Multiplier",
        "label.pattern" to "Pattern %d",
        "label.typeWithValue" to "Type %s",
        "label.patternValue" to "Pattern %d",
        "label.none" to "Select",
        "label.tps" to "TPS（节气门位置）",
        "label.map" to "MAP",
        "label.afrTarget" to "AFR 目标（空燃比）",
        "label.rpm" to "RPM",
        "label.tableInvert" to "Invert table order",
        "label.coolant" to "Coolant",
        "label.coolantShort" to "CLT",
        "label.iat" to "IAT",
        "label.afr" to "AFR（空燃比）",
        "label.o2" to "O2",
        "label.batt" to "BATT",
        "label.advance" to "ADV",
        "label.loadRpm" to "Load/RPM",
        "label.tableInvert" to "Inverter ordem da tabela",
        "label.voltageFormat" to "%.1f V",
        "label.degFormat" to "%d deg",
        "label.engineProtectionCut" to "Protection Cut",
        "label.engineProtectionRpmMin" to "Engine Protection RPM min (rpm)",
        "label.cutMethod" to "Cut Method",
        "label.cutFuel" to "燃油",
        "label.cutIgnition" to "Ignition",
        "label.cutBoth" to "Both",
        "label.cutFull" to "Full",
        "label.cutProgressive" to "Progressive",
        "label.activeProtections" to "Active Protections",
        "label.boostLimit" to "Boost Limit",
        "label.afrProtect" to "AFR Protect",
        "label.coolantProtect" to "Coolant Protect",
        "label.engineProtect" to "Engine Protect",
        "label.oilPressureProtect" to "Oil Pressure Protect",
        "label.revLimiter" to "Rev Limiter",
        "label.mainSettings" to "Main Settings",
        "label.injectors" to "喷油器数量",
        "label.injectorFlow" to "Injector lbs/hr",
        "label.injectorStaging" to "Staging",
        "label.squirtsPerCycle" to "Squirts/Cycle",
        "label.algorithm" to "Algorithm",
        "label.fuel" to "燃油",
        "label.stoichAfr" to "Stoich AFR",
        "label.mapSensor" to "MAP",
        "label.voltage" to "Voltage",
        "label.battery" to "Battery",
        "label.cylinders" to "气缸数",
        "label.displacementCc" to "Displacement cc",
        "label.stroke" to "Stroke",
        "label.compression" to "Compression",
        "label.engineType" to "Engine type",
        "label.layout" to "Layout",
        "label.primaryPhaseHigh" to "Primary phase high",
        "label.resyncEveryCycle" to "Resync every cycle",
        "label.polling" to "Polling",
        "label.captureCsvHeader" to "timestamp_ms,rpm,map_kpa,tps,coolant_c,iat_c,battery_v,advance_deg,o2",
        "label.logFilenamePrefix" to "speeduino_log",
        "label.logFilenameSuffix" to "%s.csv",
        "label.logSaveNoData" to "No captured samples yet. Start capture and wait a few seconds.",
        "label.logSaveSuccess" to "CSV saved: %s",
        "label.logSaveError" to "Error saving CSV: %s",
        "label.lastSavedLogPath" to "Last saved CSV: %s",
        "label.sensorsNotSupported" to "Sensor calibration not supported on desktop yet.",
        "label.baudRate" to "Baud",
        "label.portLabel" to "端口",
        "label.connectionTypeTcp" to "Wi-Fi/TCP",
        "label.connectionTypeUsb" to "USB 串口",
        "label.connectionTypeBluetooth" to "Bluetooth (Serial)",
        "label.bluetooth" to "Bluetooth (Serial)",
        "label.usbSerial" to "USB 串口",
        "label.wifiTcp" to "Wi-Fi/TCP",
        "label.portName" to "端口",
        "label.monitor" to "Monitor",
        "label.logs" to "Logs",
        "label.configs" to "Configs",
        "label.mapsTables" to "地图与表格",
        "label.dashboard" to "仪表盘",
        "label.app" to "App",
        "label.ignition" to "Ignition",
        "label.channel2" to "Channel 2",
        "label.channel3" to "Channel 3",
        "label.channel4" to "Channel 4",
        "unit.rpm" to "rpm",
        "unit.kpa" to "kPa",
        "unit.percent" to "%",
        "unit.celsius" to "C",
        "trigger.missingTooth" to "Missing Tooth",
        "trigger.basicDistributor" to "Basic Distributor",
        "trigger.dualWheel" to "Dual Wheel",
        "trigger.gm7x" to "GM 7X",
        "trigger.4g63" to "4G63 / Miata / 3000GT",
        "trigger.gm24x" to "GM 24X",
        "trigger.jeep2000" to "Jeep 2000",
        "trigger.audi135" to "Audi 135",
        "trigger.hondaD17" to "Honda D17",
        "trigger.miata9905" to "Miata 99-05",
        "trigger.mazdaAu" to "Mazda AU",
        "trigger.non360Dual" to "Non-360 Dual",
        "trigger.nissan360" to "Nissan 360",
        "trigger.subaru67" to "Subaru 6/7",
        "trigger.daihatsu1" to "Daihatsu +1",
        "trigger.harleyEvo" to "Harley EVO",
        "trigger.36_2_2_2" to "36-2-2-2",
        "trigger.36_2_1" to "36-2-1",
        "trigger.dsm420a" to "DSM 420a",
        "trigger.weberMarelli" to "Weber-Marelli",
        "trigger.fordSt170" to "Ford ST170",
        "trigger.drz400" to "DRZ400",
        "trigger.chryslerNgc" to "Chrysler NGC",
        "trigger.yamahaVmax1990" to "Yamaha Vmax 1990+",
        "trigger.renix" to "Renix",
        "trigger.roverMems" to "Rover MEMS",
        "trigger.k6a" to "K6A",
        "trigger.singleToothCam" to "Single tooth cam",
        "trigger.4_1_cam" to "4-1 cam",
        "trigger.rover532cam" to "Rover 5-3-2 cam",
        "trigger.toyota3tooth" to "Toyota 3 Tooth",
    )

    fun forLanguage(language: AppLanguage): Map<String, String> {
        return when (language) {
            AppLanguage.PT -> PT
            AppLanguage.ES -> ES
            AppLanguage.FR -> FR
            AppLanguage.ID -> ID
            AppLanguage.ZH -> ZH
            else -> EN
        }
    }
}

object AppSettings {
    private val settingsDir: Path = Paths.get(
        System.getProperty("user.home"),
        ".speeduino-manager-desktop"
    )
    private val settingsFile: Path = settingsDir.resolve("settings.properties")

    fun loadLanguage(): AppLanguage {
        if (!Files.exists(settingsFile)) {
            return AppLanguage.PT
        }

        val properties = Properties()
        return try {
            Files.newInputStream(settingsFile).use { input ->
                properties.load(input)
            }
            AppLanguage.fromCode(properties.getProperty("language"))
        } catch (_: Exception) {
            AppLanguage.PT
        }
    }

    fun saveLanguage(language: AppLanguage) {
        val properties = Properties()
        properties.setProperty("language", language.code)
        try {
            Files.createDirectories(settingsDir)
            Files.newOutputStream(settingsFile).use { output ->
                properties.store(output, "SpeeduinoManager Desktop Settings")
            }
        } catch (_: Exception) {
            // Ignore settings persistence errors.
        }
    }
}

object LocalizationManager {
    val language = MutableStateFlow(AppSettings.loadLanguage())

    fun setLanguage(language: AppLanguage) {
        if (this.language.value == language) return
        this.language.value = language
        AppSettings.saveLanguage(language)
    }

    fun currentStrings(): Strings {
        return Strings(Translations.forLanguage(language.value))
    }
}
